// proteins.js — curated database of 30 well-studied human proteins.
// Each entry is what a researcher would currently have to assemble from
// Wikipedia, UniProt, PDB, NCBI Gene, and a review article.

export const PROTEINS = {
  p53: {
    gene: "TP53",
    uniprot: "P04637",
    length: 393,
    role: "tumour suppressor",
    function: "guardian of the genome; activates DNA repair, cell-cycle arrest, or apoptosis in response to cellular stress (DNA damage, oncogene activation, hypoxia).",
    domains: ["TAD (1-60)", "PRD (60-94)", "DBD (94-292)", "TET (323-356)", "CTD (363-393)"],
    diseases: ["Li-Fraumeni syndrome", "somatic mutations in ~50% of human cancers"],
    interacts: ["MDM2", "MDMX", "ATM", "CBP", "p300", "p21/CDKN1A", "BAX"],
    pathway: "p53 signalling; apoptosis; cell-cycle regulation",
    localization: "nucleus, cytoplasm",
  },
  hemoglobin: {
    gene: "HBB",
    uniprot: "P68871",
    length: 147,
    role: "oxygen transport",
    function: "tetrameric (α2β2) haem-containing protein in erythrocytes; transports O2 from lungs to tissues and CO2 back; cooperative binding.",
    domains: ["globin fold", "haem-binding pocket"],
    diseases: ["sickle-cell disease (Glu6Val)", "β-thalassaemia", "methaemoglobinaemia"],
    interacts: ["haptoglobin", "2,3-BPG", "O2", "CO2"],
    pathway: "gas transport; erythrocyte homeostasis",
    localization: "erythrocyte cytoplasm",
  },
  insulin: {
    gene: "INS",
    uniprot: "P01308",
    length: 110,
    role: "hormone",
    function: "regulates glucose homeostasis by promoting glucose uptake in muscle and adipose tissue and suppressing hepatic gluconeogenesis.",
    domains: ["A chain (21 aa)", "B chain (30 aa)", "signal peptide + C-peptide in proinsulin"],
    diseases: ["type 1 diabetes (autoimmune destruction of β cells)", "type 2 diabetes (insulin resistance)", "rare monogenic diabetes (MODY)"],
    interacts: ["insulin receptor (INSR)", "IRS1/IRS2", "IGF1R"],
    pathway: "insulin signalling; PI3K-AKT-mTOR",
    localization: "secreted; β-cell granules",
  },
  egfr: {
    gene: "EGFR",
    uniprot: "P00533",
    length: 1210,
    role: "receptor tyrosine kinase",
    function: "binds EGF family ligands; homodimerises; autophosphorylates; activates RAS-MAPK, PI3K-AKT, JAK-STAT. Over-activation drives proliferation in epithelial cancers.",
    domains: ["extracellular L1/CR1/L2/CR2", "transmembrane", "juxtamembrane", "kinase domain", "C-terminal tail"],
    diseases: ["non-small-cell lung cancer (EGFR L858R, exon 19 del, T790M resistance)", "glioblastoma (EGFRvIII)", "colorectal cancer"],
    interacts: ["HER2/ERBB2", "HER3", "GRB2", "SHC", "PI3K", "SRC"],
    pathway: "EGFR signalling; RAS-MAPK; PI3K-AKT",
    localization: "plasma membrane",
  },
  brca1: {
    gene: "BRCA1",
    uniprot: "P38398",
    length: 1863,
    role: "tumour suppressor; DNA repair",
    function: "E3 ubiquitin ligase; scaffold for homologous-recombination DNA repair at double-strand breaks; regulates cell-cycle checkpoints.",
    domains: ["RING (1-109)", "coiled-coil", "BRCT tandem (1649-1863)"],
    diseases: ["hereditary breast and ovarian cancer", "Fanconi anaemia (biallelic loss)"],
    interacts: ["BARD1", "BRCA2", "PALB2", "RAD51", "CHEK2", "ATM"],
    pathway: "homologous recombination; G2/M checkpoint",
    localization: "nucleus",
  },
  brca2: {
    gene: "BRCA2",
    uniprot: "P51587",
    length: 3418,
    role: "tumour suppressor; DNA repair",
    function: "loads RAD51 onto ssDNA at double-strand breaks; central to homologous recombination repair.",
    domains: ["8× BRC repeats", "DBD (helical + OB folds)", "TR2 C-terminal RAD51-binding"],
    diseases: ["hereditary breast, ovarian, pancreatic, prostate cancer", "Fanconi anaemia group D1"],
    interacts: ["RAD51", "DSS1", "PALB2", "BRCA1 (via PALB2)"],
    pathway: "homologous recombination",
    localization: "nucleus",
  },
  tnf: {
    gene: "TNF",
    uniprot: "P01375",
    length: 233,
    role: "cytokine",
    function: "pro-inflammatory cytokine produced primarily by macrophages; cleaved by TACE/ADAM17 from membrane to soluble trimer; binds TNFR1/TNFR2.",
    domains: ["intracellular", "transmembrane", "extracellular TNF homology"],
    diseases: ["rheumatoid arthritis", "Crohn disease", "psoriasis — all treated with anti-TNF biologics"],
    interacts: ["TNFR1/TNFRSF1A", "TNFR2/TNFRSF1B", "TRADD", "TRAF2", "RIPK1"],
    pathway: "NF-κB; MAPK; extrinsic apoptosis",
    localization: "plasma membrane; secreted",
  },
  il6: {
    gene: "IL6",
    uniprot: "P05231",
    length: 212,
    role: "cytokine",
    function: "pleiotropic cytokine; acute-phase response, B-cell differentiation, hepatic CRP induction; implicated in cytokine storm.",
    domains: ["four-helix bundle cytokine fold"],
    diseases: ["rheumatoid arthritis", "Castleman disease", "COVID-19 cytokine storm — tocilizumab targets IL6R"],
    interacts: ["IL6R", "gp130/IL6ST", "JAK1/JAK2", "STAT3"],
    pathway: "JAK-STAT (STAT3)",
    localization: "secreted",
  },
  ace2: {
    gene: "ACE2",
    uniprot: "Q9BYF1",
    length: 805,
    role: "carboxypeptidase; receptor",
    function: "converts angiotensin II to angiotensin-(1-7); counter-regulator of the renin-angiotensin system. Serves as entry receptor for SARS-CoV and SARS-CoV-2 spike protein.",
    domains: ["peptidase M2", "collectrin-like transmembrane"],
    diseases: ["hypertension modulation", "COVID-19 (spike binding)", "cardiovascular disease"],
    interacts: ["angiotensin II", "angiotensin-(1-7)", "SARS-CoV-2 spike", "TMPRSS2 (co-factor for viral entry)"],
    pathway: "renin-angiotensin system",
    localization: "plasma membrane; secreted soluble form",
  },
  cftr: {
    gene: "CFTR",
    uniprot: "P13569",
    length: 1480,
    role: "chloride channel",
    function: "cAMP-regulated chloride channel in epithelial cells; regulates salt and water transport across airway, intestinal, and pancreatic epithelia.",
    domains: ["MSD1 (TM1-6)", "NBD1", "R domain", "MSD2 (TM7-12)", "NBD2"],
    diseases: ["cystic fibrosis (ΔF508 most common; >2000 mutations known)"],
    interacts: ["NHERF1/SLC9A3R1", "AMPK", "ATP (gating)"],
    pathway: "chloride transport; ABC transporter family",
    localization: "apical plasma membrane of epithelia",
  },
  huntingtin: {
    gene: "HTT",
    uniprot: "P42858",
    length: 3142,
    role: "scaffold protein",
    function: "large scaffold with HEAT repeats; roles in vesicular transport, autophagy, mitochondrial function; essential in development.",
    domains: ["polyQ tract (exon 1)", "HEAT repeats (multiple)"],
    diseases: ["Huntington disease — autosomal dominant; CAG expansion >36 → pathogenic polyQ huntingtin"],
    interacts: ["HAP1", "HIP1", "dynactin", "p53", "BDNF"],
    pathway: "autophagy; vesicle trafficking",
    localization: "cytoplasm; nucleus (fragments)",
  },
  app: {
    gene: "APP",
    uniprot: "P05067",
    length: 770,
    role: "membrane protein; amyloid precursor",
    function: "single-pass transmembrane; cleaved by α/β/γ-secretases. β+γ cleavage yields amyloid-β peptide (Aβ40, Aβ42) that forms plaques in Alzheimer disease.",
    domains: ["E1 (GFLD+CuBD)", "E2 (CAPPD)", "Aβ domain", "AICD cytoplasmic"],
    diseases: ["Alzheimer disease (familial mutations + sporadic)"],
    interacts: ["BACE1", "presenilin/PSEN1 (γ-secretase)", "APBB1/FE65"],
    pathway: "amyloid processing; Alzheimer pathology",
    localization: "plasma membrane; endosomes",
  },
  synuclein: {
    gene: "SNCA",
    uniprot: "P37840",
    length: 140,
    role: "synaptic protein",
    function: "small acidic protein; abundant at presynaptic terminals; membrane-binding and SNARE-complex chaperoning. Aggregates form Lewy bodies.",
    domains: ["N-terminal amphipathic repeats", "NAC (aggregation-prone core)", "acidic C-terminal tail"],
    diseases: ["Parkinson disease", "Lewy body dementia", "multiple system atrophy"],
    interacts: ["VAMP2/synaptobrevin", "lipid membranes", "dopamine"],
    pathway: "synaptic vesicle trafficking",
    localization: "presynaptic terminal; cytoplasm",
  },
  dystrophin: {
    gene: "DMD",
    uniprot: "P11532",
    length: 3685,
    role: "cytoskeletal linker",
    function: "links actin cytoskeleton to the extracellular matrix through the dystrophin-glycoprotein complex; stabilises muscle fibres during contraction.",
    domains: ["actin-binding (N-term)", "24 spectrin repeats", "cysteine-rich domain", "C-terminal (binds syntrophin, dystrobrevin)"],
    diseases: ["Duchenne muscular dystrophy (null)", "Becker muscular dystrophy (truncated)"],
    interacts: ["actin", "β-dystroglycan", "syntrophin", "neuronal NOS"],
    pathway: "dystrophin-associated protein complex",
    localization: "sarcolemma",
  },
  ldlr: {
    gene: "LDLR",
    uniprot: "P01130",
    length: 860,
    role: "receptor",
    function: "binds LDL particles and mediates receptor-mediated endocytosis; primary pathway for clearing serum cholesterol.",
    domains: ["ligand-binding (7 LA repeats)", "EGF precursor homology", "O-linked sugar", "transmembrane", "cytoplasmic (FXNPxY motif)"],
    diseases: ["familial hypercholesterolaemia (autosomal dominant)"],
    interacts: ["LDL (apoB)", "PCSK9 (promotes degradation)", "ARH/LDLRAP1"],
    pathway: "cholesterol homeostasis; endocytosis",
    localization: "plasma membrane; clathrin-coated pits",
  },
  collagen1: {
    gene: "COL1A1",
    uniprot: "P02452",
    length: 1464,
    role: "extracellular matrix",
    function: "α1 chain of type I collagen; assembles with α2 into triple helix; dominant structural protein in bone, tendon, skin, dentine.",
    domains: ["triple-helical (Gly-X-Y repeats, ~1000 aa)", "N-propeptide", "C-propeptide"],
    diseases: ["osteogenesis imperfecta", "Ehlers-Danlos syndrome (classical + arthrochalasia types)"],
    interacts: ["COL1A2", "integrins (α1β1, α2β1)", "DDR1/DDR2", "fibronectin"],
    pathway: "ECM assembly",
    localization: "extracellular",
  },
  actin: {
    gene: "ACTB",
    uniprot: "P60709",
    length: 375,
    role: "cytoskeletal protein",
    function: "β-actin; polymerises into F-actin filaments; core of the cytoskeleton; drives cell motility, division, shape change, intracellular transport.",
    domains: ["4 subdomains (ATPase fold)"],
    diseases: ["Baraitser-Winter syndrome (ACTB mutations)", "constitutive reference gene in expression studies"],
    interacts: ["myosin", "profilin", "cofilin", "gelsolin", "Arp2/3 complex", "WASP/N-WASP"],
    pathway: "cytoskeletal dynamics",
    localization: "cytoplasm",
  },
  myosin7: {
    gene: "MYH7",
    uniprot: "P12883",
    length: 1935,
    role: "motor protein",
    function: "β-cardiac myosin heavy chain; slow-twitch skeletal + cardiac muscle; ATP-driven actin sliding underlies contraction.",
    domains: ["motor/head", "neck (light-chain-binding)", "coiled-coil tail"],
    diseases: ["hypertrophic cardiomyopathy (MYH7 most common gene)", "dilated cardiomyopathy", "Laing distal myopathy"],
    interacts: ["actin", "myosin light chains (MYL2/MYL3)", "titin"],
    pathway: "muscle contraction; sarcomere assembly",
    localization: "sarcomere thick filament",
  },
  gapdh: {
    gene: "GAPDH",
    uniprot: "P04406",
    length: 335,
    role: "glycolytic enzyme",
    function: "catalyses the 6th step of glycolysis (glyceraldehyde-3-phosphate → 1,3-bisphosphoglycerate). Moonlighting roles in apoptosis, nuclear functions.",
    domains: ["NAD-binding (Rossmann fold)", "catalytic"],
    diseases: ["common reference gene in mRNA/protein quantification", "altered in many cancers"],
    interacts: ["NAD+/NADH", "GAPDH tetramer", "Siah1 (apoptotic translocation)"],
    pathway: "glycolysis",
    localization: "cytoplasm; nucleus under stress",
  },
  tubulin: {
    gene: "TUBA1A",
    uniprot: "Q71U36",
    length: 451,
    role: "cytoskeletal protein",
    function: "α-tubulin; dimerises with β-tubulin; polymerises head-to-tail into microtubules that form the mitotic spindle and cytoskeletal tracks.",
    domains: ["GTP-binding", "α-β interface", "C-terminal tail (post-translational tyrosination/detyrosination)"],
    diseases: ["tubulinopathies (lissencephaly)", "target of taxanes + vinca alkaloids in chemotherapy"],
    interacts: ["β-tubulin (TUBB)", "MAPs (MAP2, tau)", "kinesin", "dynein"],
    pathway: "microtubule dynamics; mitosis; intracellular transport",
    localization: "cytoplasm",
  },
  histone3: {
    gene: "H3-3A",
    uniprot: "P84243",
    length: 136,
    role: "chromatin structure",
    function: "H3.3 variant; wraps DNA with H2A/H2B/H4 into nucleosomes; post-translational modifications (H3K4me3, H3K27me3, H3K9ac) encode the epigenetic state.",
    domains: ["histone fold (3 α-helices)"],
    diseases: ["H3.3 K27M in diffuse midline glioma; G34R/V in paediatric glioblastoma"],
    interacts: ["DNA (wrapping)", "HAT/HDAC enzymes", "methyltransferases (PRC2, MLL)", "ATRX/DAXX chaperones"],
    pathway: "chromatin regulation; transcription",
    localization: "nucleus",
  },
  ubiquitin: {
    gene: "UBB",
    uniprot: "P0CG47",
    length: 76,
    role: "protein-degradation tag",
    function: "76-aa protein; conjugated to substrate lysines via E1-E2-E3 cascade; chains direct proteins to the 26S proteasome.",
    domains: ["ubiquitin fold (β-grasp)"],
    diseases: ["UBB+1 frame-shift variant enriched in Alzheimer + Down syndrome brain"],
    interacts: ["E1 (UBA1)", "E2 enzymes", "E3 ligases (MDM2, SKP1-CUL1-F-box, etc.)", "proteasome"],
    pathway: "ubiquitin-proteasome system",
    localization: "cytoplasm; nucleus",
  },
  p21: {
    gene: "CDKN1A",
    uniprot: "P38936",
    length: 164,
    role: "cyclin-dependent kinase inhibitor",
    function: "intrinsically disordered; binds and inhibits CDK2 and CDK4/6 complexes; major effector of p53-induced G1 arrest.",
    domains: ["N-terminal CDK/cyclin-binding", "C-terminal PCNA-binding"],
    diseases: ["tumour suppressor; loss associated with various cancers"],
    interacts: ["CDK2/cyclin E", "CDK4/cyclin D", "PCNA", "p53 (induces it)"],
    pathway: "p53 signalling; G1/S checkpoint",
    localization: "nucleus",
  },
  ras: {
    gene: "HRAS",
    uniprot: "P01112",
    length: 189,
    role: "small GTPase",
    function: "membrane-anchored GTPase cycling between GDP- (off) and GTP- (on) states; activates RAF-MEK-ERK and PI3K-AKT. Founding member of the Ras superfamily.",
    domains: ["G-domain (P-loop, switch I, switch II)", "hypervariable region (C-terminal, CAAX motif)"],
    diseases: ["Costello syndrome (germline HRAS)", "somatic RAS (KRAS/HRAS/NRAS) mutations in ~30% of human cancers"],
    interacts: ["RAF", "PI3K", "GEFs (SOS1)", "GAPs (NF1, p120GAP)"],
    pathway: "RAS-MAPK; PI3K-AKT",
    localization: "plasma membrane (prenylation)",
  },
  myc: {
    gene: "MYC",
    uniprot: "P01106",
    length: 439,
    role: "transcription factor",
    function: "bHLH-LZ transcription factor; heterodimerises with MAX; activates genes for cell growth, metabolism, ribosome biogenesis; short-lived, tightly regulated.",
    domains: ["MycBoxes I-IV (N-terminal)", "bHLH-LZ (C-terminal)"],
    diseases: ["Burkitt lymphoma (MYC-IG translocation)", "amplification in many cancers; driver oncogene"],
    interacts: ["MAX", "MAD/MXD (antagonists)", "MIZ1", "TRRAP + histone acetyltransferases"],
    pathway: "MYC target network; ribosome biogenesis; metabolism",
    localization: "nucleus",
  },
  bcl2: {
    gene: "BCL2",
    uniprot: "P10415",
    length: 239,
    role: "apoptosis regulator",
    function: "anti-apoptotic; inhibits BAX/BAK pore formation in mitochondrial outer membrane; prevents cytochrome-c release.",
    domains: ["BH1-BH4", "transmembrane (C-terminal)"],
    diseases: ["follicular lymphoma (t(14;18) IGH-BCL2 translocation)", "target of venetoclax in CLL, AML"],
    interacts: ["BAX", "BAK", "BH3-only proteins (BIM, BID, PUMA, NOXA)"],
    pathway: "intrinsic apoptosis",
    localization: "mitochondrial outer membrane; ER",
  },
  caspase3: {
    gene: "CASP3",
    uniprot: "P42574",
    length: 277,
    role: "executioner caspase",
    function: "cysteine protease; activated from procaspase-3 by caspase-8 or -9; cleaves hundreds of substrates (PARP, ICAD, lamins) to execute apoptosis.",
    domains: ["prodomain (cleaved)", "large subunit", "small subunit"],
    diseases: ["aberrant apoptosis in neurodegeneration; resistance in cancers"],
    interacts: ["procaspase-3 (substrate form)", "caspase-8", "caspase-9", "XIAP (inhibitor)"],
    pathway: "apoptosis execution",
    localization: "cytoplasm",
  },
  drd2: {
    gene: "DRD2",
    uniprot: "P14416",
    length: 443,
    role: "G-protein-coupled receptor",
    function: "dopamine D2 receptor; Gi/o-coupled; inhibits adenylyl cyclase; central target of antipsychotics (haloperidol, risperidone) and Parkinson's agonists.",
    domains: ["7 transmembrane helices (class A GPCR)"],
    diseases: ["schizophrenia (target of antipsychotics)", "Parkinson disease", "addiction vulnerability (Taq1A allele)"],
    interacts: ["dopamine", "Gαi/o", "β-arrestin", "antipsychotics, agonists"],
    pathway: "dopaminergic signalling",
    localization: "plasma membrane (CNS synapses)",
  },
  cd4: {
    gene: "CD4",
    uniprot: "P01730",
    length: 458,
    role: "immune co-receptor",
    function: "co-receptor on helper T cells; binds MHC class II on antigen-presenting cells, stabilising the TCR-peptide-MHC complex; recruits Lck kinase intracellularly.",
    domains: ["4 Ig-like extracellular (D1-D4)", "transmembrane", "cytoplasmic (Lck binding)"],
    diseases: ["HIV entry receptor (gp120 binds D1)", "CD4+ T-cell depletion defines AIDS"],
    interacts: ["MHC class II (HLA-DR/DQ/DP)", "Lck", "HIV-1 gp120", "CCR5/CXCR4 (HIV co-receptors)"],
    pathway: "T-cell receptor signalling",
    localization: "plasma membrane (T helper cells)",
  },
};

export const PROTEIN_ALIASES = {
  // canonical name aliases, lowercase → key
  "tp53": "p53",
  "p-53": "p53",
  "hba": "hemoglobin",
  "hbb": "hemoglobin",
  "haemoglobin": "hemoglobin",
  "ins": "insulin",
  "egf receptor": "egfr",
  "egf-receptor": "egfr",
  "her1": "egfr",
  "erbb1": "egfr",
  "tumor necrosis factor": "tnf",
  "tumour necrosis factor": "tnf",
  "interleukin-6": "il6",
  "interleukin 6": "il6",
  "il-6": "il6",
  "angiotensin-converting enzyme 2": "ace2",
  "htt": "huntingtin",
  "amyloid precursor protein": "app",
  "amyloid-precursor-protein": "app",
  "alpha-synuclein": "synuclein",
  "α-synuclein": "synuclein",
  "snca": "synuclein",
  "dmd": "dystrophin",
  "ldl receptor": "ldlr",
  "type i collagen": "collagen1",
  "collagen i": "collagen1",
  "col1a1": "collagen1",
  "β-actin": "actin",
  "beta-actin": "actin",
  "actb": "actin",
  "cardiac myosin": "myosin7",
  "myh7": "myosin7",
  "tubulin alpha": "tubulin",
  "α-tubulin": "tubulin",
  "histone h3": "histone3",
  "h3": "histone3",
  "h3-3": "histone3",
  "ub": "ubiquitin",
  "cdkn1a": "p21",
  "waf1": "p21",
  "hras": "ras",
  "k-ras": "ras",
  "kras": "ras",
  "c-myc": "myc",
  "b-cell lymphoma 2": "bcl2",
  "casp3": "caspase3",
  "caspase-3": "caspase3",
  "dopamine d2 receptor": "drd2",
  "d2 receptor": "drd2",
  "cd-4": "cd4",
};

export function resolveProtein(name) {
  const lc = name.toLowerCase().trim();
  if (PROTEINS[lc]) return lc;
  if (PROTEIN_ALIASES[lc]) return PROTEIN_ALIASES[lc];
  // try gene-symbol matching
  for (const [key, p] of Object.entries(PROTEINS)) {
    if (p.gene && p.gene.toLowerCase() === lc) return key;
  }
  return null;
}
