"""
Master script to generate all figures for Buhera OS papers.

Generates 5 comprehensive figures:
1. Figure 1: Categorical Sorting Performance
2. Figure 2: Categorical-Physical Commutation
3. Figure 3: Ternary Partition Trees
4. Figure 4: S-Entropy Coordinate Addressing
5. Figure 5: Categorical Processor Architecture

Each figure is a 4-panel layout with publication-quality graphics.
"""

import sys
from pathlib import Path
import matplotlib.pyplot as plt

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from visualizations.figure_sorting import generate_sorting_figure
from visualizations.figure_commutation import generate_commutation_figure
from visualizations.figure_partition_tree import generate_partition_tree_figure
from visualizations.figure_s_coordinates import generate_s_coordinate_figure
from visualizations.figure_processor import generate_processor_figure


def generate_all_figures(output_dir: str = "driven/figures"):
    """Generate all paper figures."""

    print("=" * 80)
    print(" " * 20 + "GENERATING BUHERA OS FIGURES")
    print("=" * 80)
    print()

    # Create output directory
    Path(output_dir).mkdir(exist_ok=True, parents=True)

    figures = []

    # Figure 1: Sorting
    print("[1/5] Generating sorting performance figure...")
    try:
        fig1 = generate_sorting_figure(f"{output_dir}/figure_sorting.pdf")
        figures.append(("Figure 1: Sorting", fig1))
        plt.close(fig1)
    except Exception as e:
        print(f"  [FAIL] Error generating sorting figure: {e}")

    # Figure 2: Commutation
    print("[2/5] Generating commutation relations figure...")
    try:
        fig2 = generate_commutation_figure(f"{output_dir}/figure_commutation.pdf")
        figures.append(("Figure 2: Commutation", fig2))
        plt.close(fig2)
    except Exception as e:
        print(f"  [FAIL] Error generating commutation figure: {e}")

    # Figure 3: Partition Trees
    print("[3/5] Generating partition tree figure...")
    try:
        fig3 = generate_partition_tree_figure(f"{output_dir}/figure_partition_tree.pdf")
        figures.append(("Figure 3: Partition Trees", fig3))
        plt.close(fig3)
    except Exception as e:
        print(f"  [FAIL] Error generating partition tree figure: {e}")

    # Figure 4: S-Coordinates
    print("[4/5] Generating S-coordinate addressing figure...")
    try:
        fig4 = generate_s_coordinate_figure(f"{output_dir}/figure_s_coordinates.pdf")
        figures.append(("Figure 4: S-Coordinates", fig4))
        plt.close(fig4)
    except Exception as e:
        print(f"  [FAIL] Error generating S-coordinate figure: {e}")

    # Figure 5: Processor
    print("[5/5] Generating categorical processor figure...")
    try:
        fig5 = generate_processor_figure(f"{output_dir}/figure_processor.pdf")
        figures.append(("Figure 5: Processor", fig5))
        plt.close(fig5)
    except Exception as e:
        print(f"  [FAIL] Error generating processor figure: {e}")

    print()
    print("=" * 80)
    print(" FIGURE GENERATION COMPLETE")
    print("=" * 80)
    print()
    print(f"Total figures generated: {len(figures)}/5")
    print(f"Output directory: {output_dir}/")
    print()
    print("Generated files:")
    for name, _ in figures:
        print(f"  - {name}")

    print()
    print("Files saved in both PDF (vector) and PNG (raster) formats.")
    print()

    # Create a LaTeX include file
    create_latex_includes(output_dir)

    return figures


def create_latex_includes(output_dir: str):
    """Create a LaTeX file with figure includes for easy insertion into paper."""

    latex_content = r"""% Buhera OS Figure Includes
% Auto-generated by generate_all_figures.py

% Figure 1: Categorical Sorting Performance
\begin{figure*}[htbp]
    \centering
    \includegraphics[width=\textwidth]{figures/figure_sorting.pdf}
    \caption{Categorical Sorting Performance. (a) Complexity scaling showing O($\log_3 N$) categorical vs O($N \log N$) conventional with perfect fit quality ($R^2 = 1.0$). (b) Speedup scaling demonstrating increasing advantage with problem size. (c) Energy efficiency landscape across problem sizes and trials. (d) Speedup matrix across different data distributions and sizes.}
    \label{fig:sorting}
\end{figure*}

% Figure 2: Categorical-Physical Commutation Relations
\begin{figure*}[htbp]
    \centering
    \includegraphics[width=\textwidth]{figures/figure_commutation.pdf}
    \caption{Categorical-Physical Commutation Relations. (a) Commutator magnitude matrix showing all relations $< 10^{-10}$ (numerical zero). (b) Validation results demonstrating all nine commutation tests pass within tolerance. (c) Operator space visualization showing categorical and physical operators form commuting sets. (d) Finite size scaling analysis confirming commutators vanish in infinite dimensional limit.}
    \label{fig:commutation}
\end{figure*}

% Figure 3: Ternary Partition Tree Architecture
\begin{figure*}[htbp]
    \centering
    \includegraphics[width=\textwidth]{figures/figure_partition_tree.pdf}
    \caption{Ternary Partition Tree Architecture. (a) Hierarchical ternary tree structure with $3^d$ leaves at depth $d$. (b) Navigation complexity comparison showing categorical O($\log_3 N$) advantage over binary O($\log_2 N$) and linear O($N$) approaches. (c) 3D partition space visualization showing hierarchical cell structure. (d) Storage capacity scaling for ternary, binary, and quantum state spaces.}
    \label{fig:partition_tree}
\end{figure*}

% Figure 4: S-Entropy Coordinate Addressing
\begin{figure*}[htbp]
    \centering
    \includegraphics[width=\textwidth]{figures/figure_s_coordinates.pdf}
    \caption{S-Entropy Coordinate Addressing. (a) S-coordinate space with ternary partition regions labeled by coordinate pairs. (b) Hierarchical address resolution trajectory showing logarithmic refinement to target. (c) Full 3D S-entropy space $(S_k, S_t, S_e)$ with partition boundaries. (d) Entropy component composition for different physical systems.}
    \label{fig:s_coordinates}
\end{figure*}

% Figure 5: Categorical Processor Operation
\begin{figure*}[htbp]
    \centering
    \includegraphics[width=\textwidth]{figures/figure_processor.pdf}
    \caption{Categorical Processor Operation. (a) Processing pipeline showing five stages from input to output with complexity annotations. (b) Trajectory completion vs forward simulation demonstrating speedup advantage. (c) 3D state space trajectories comparing forward simulation (spiral) to categorical navigation (direct path) with completion morphism. (d) Penultimate state detection showing distance convergence and single-step completion.}
    \label{fig:processor}
\end{figure*}
"""

    latex_file = Path(output_dir) / "figure_includes.tex"
    with open(latex_file, 'w') as f:
        f.write(latex_content)

    print(f"[OK] LaTeX include file created: {latex_file}")
    print()
    print("To use in your paper, add to your LaTeX document:")
    print("  \\input{figures/figure_includes.tex}")
    print()


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Generate all Buhera OS figures")
    parser.add_argument("--output", "-o", default="driven/figures",
                       help="Output directory for figures")
    args = parser.parse_args()

    figures = generate_all_figures(args.output)

    print("Done! All figures ready for publication.")
