// Every example in every knowledge pack is grammatical by the language's OWN
// compiler (specification 04, rules L1 + §5). A pack that grounds generation
// with an invalid example teaches the model to write invalid code.
import test from "node:test";
import assert from "node:assert/strict";
import { readdirSync, readFileSync, existsSync } from "node:fs";
import path from "node:path";

import { listDsls, validate } from "../src/lib/purpose/dsl/validators.js";

const PACKS = path.join(process.cwd(), "knowledge-packs");

for (const id of readdirSync(PACKS)) {
  const ref = path.join(PACKS, id, "reference.md");
  if (!existsSync(ref)) continue;
  test(`pack ${id}: tagged examples validate with the real compiler`, () => {
    const md = readFileSync(ref, "utf8");
    const blocks = [...md.matchAll(/```([\w-]+)\r?\n([\s\S]*?)```/g)].filter(([, lang]) => listDsls().includes(lang));
    // Generated packs must carry examples; the hand-written vaHera pack tags none.
    if (md.includes("GENERATED by scripts/build-packs.mjs")) assert.ok(blocks.length >= 1, `${id}: no tagged examples`);
    for (const [, lang, body] of blocks) {
      const v = validate(lang, body);
      assert.equal(v.ok, true, `${id}: a \`${lang}\` example is rejected: ${JSON.stringify(v.errors)}\n${body}`);
    }
  });
}
