// Tests for reading a specification: the model from property tables (the
// markup DCAT-AP 3.0.1 uses) and from LinkML (DCAT-AP+), the diagrams drawn
// from a model, and the comparison of two models.
import test from "node:test";
import assert from "node:assert/strict";

import { fromLinkML, fromPropertyTables, modelFrom, parseCard } from "../src/lib/server/spec-model.js";
import { classDiagram, flowDiagram, flowEdges, neighbourhood } from "../src/lib/spec/diagram.js";
import { compare, norm } from "../src/lib/spec/compare.js";

// The shape of DCAT-AP 3.0.1's class sections, cut down: a section per class,
// a property table whose rows carry id and resource, a range linked inside
// the page, and a datatype anchored in a table cell.
const HTML = `<!DOCTYPE html><html><head><title>DCAT-AP 3.0.1</title><script>var e = [{ name: "Someone" }];</script></head><body>
<section id="main-entities"><h2>Main Entities</h2>
<section id="Dataset"><h3>Dataset</h3>
<dl><dt>Definition</dt><dd>A conceptual entity that represents the information published.</dd></dl>
<table class="data-table simple"><thead><tr><th>Property</th><th>Range</th><th>Card</th><th>Definition</th><th>Usage</th><th>Reuse</th></tr></thead>
<tbody>
<tr id="Dataset.title" resource="http://purl.org/dc/terms/title"><td><a href="http://purl.org/dc/terms/title">title</a></td><td><a href="#Literal">Literal</a></td><td>1..n</td><td>A name given to the Dataset.</td><td></td><td>A</td></tr>
<tr id="Dataset.datasetdistribution" resource="http://www.w3.org/ns/dcat#distribution"><td><a href="http://www.w3.org/ns/dcat#distribution">dataset distribution</a></td><td><a href="#Distribution">Distribution</a></td><td>0..*</td><td>An available Distribution.</td><td></td><td>A</td></tr>
<tr id="Dataset.wasgeneratedby" resource="http://www.w3.org/ns/prov#wasGeneratedBy"><td><a href="http://www.w3.org/ns/prov#wasGeneratedBy">was generated by</a></td><td><a href="#Activity">Activity</a></td><td>0..*</td><td>An activity that generated the dataset.</td><td></td><td>A</td></tr>
<tr id="Dataset.modificationdate" resource="http://purl.org/dc/terms/modified"><td><a href="http://purl.org/dc/terms/modified">modification date</a></td><td><a href="#TemporalLiteral">Temporal Literal</a></td><td>0..1</td><td>The most recent date.</td><td></td><td>A</td></tr>
</tbody></table></section>
<section id="Distribution"><h3>Distribution</h3>
<table><thead><tr><th>Property</th><th>Range</th><th>Card</th><th>Definition</th></tr></thead><tbody>
<tr id="Distribution.accessURL" resource="http://www.w3.org/ns/dcat#accessURL"><td><a href="x">access URL</a></td><td><a href="#Resource">Resource</a></td><td>1..n</td><td>A URL.</td></tr>
</tbody></table></section></section>
<section id="supportive-entities"><h2>Supportive Entities</h2>
<section><h3 id="Activity">Activity</h3><dl><dt>Definition</dt><dd>An activity.</dd></dl></section>
<section><h3 id="Resource">Resource</h3></section>
<section><h3 id="Literal">Literal</h3></section></section>
<section><h2>Datatypes</h2><table><tbody><tr><td><div id="TemporalLiteral"><a href="#">Temporal Literal</a></div></td></tr></tbody></table></section>
</body></html>`;

// DCAT-AP+'s pattern, cut down: Dataset.was_generated_by made required and
// narrowed to DataGeneratingActivity, which uses a Plan and an evaluated
// entity and is carried out by a Device.
const LINKML = `id: https://w3id.org/nfdi-de/dcat-ap-plus/
name: dcat-ap-plus
title: DCAT-AP-PLUS
version: "0.1.0rc4"
prefixes:
  prov: http://www.w3.org/ns/prov#
  dcat: http://www.w3.org/ns/dcat#
  dcterms: http://purl.org/dc/terms/
default_range: string
slots:
  title:
    slot_uri: dcterms:title
  dataset_distribution:
    slot_uri: dcat:distribution
  was_generated_by:
    slot_uri: prov:wasGeneratedBy
  realized_plan:
    slot_uri: prov:used
    range: Plan
  evaluated_entity:
    slot_uri: prov:used
    range: EvaluatedEntity
  carried_out_by:
    slot_uri: prov:wasAssociatedWith
    range: AgenticEntity
classes:
  Dataset:
    class_uri: dcat:Dataset
    slots: [title, dataset_distribution, was_generated_by]
    slot_usage:
      title:
        required: true
        multivalued: true
      dataset_distribution:
        range: Distribution
        multivalued: true
      was_generated_by:
        range: DataGeneratingActivity
        required: true
        multivalued: true
        notes: [stricter than DCAT-AP]
  Distribution:
    class_uri: dcat:Distribution
  Activity:
    class_uri: prov:Activity
    slots: [carried_out_by]
  DataGeneratingActivity:
    is_a: Activity
    class_uri: prov:Activity
    slots: [realized_plan, evaluated_entity]
  Plan:
    class_uri: prov:Plan
  EvaluatedEntity:
    class_uri: prov:Entity
  AgenticEntity:
    class_uri: prov:Agent
  Device:
    is_a: AgenticEntity
`;

test("cardinalities", () => {
  assert.deepEqual(parseCard("1..n"), { min: 1, max: "*", card: "1..*" });
  assert.deepEqual(parseCard(" 0..* "), { min: 0, max: "*", card: "0..*" });
  assert.deepEqual(parseCard("1"), { min: 1, max: 1, card: "1" });
  assert.equal(parseCard("several").min, 0);
});

test("a property-table specification: classes, ranges, obligations, datatypes", () => {
  const m = modelFrom(HTML, "https://example.org/dcat-ap/");
  assert.equal(m.kind, "property-tables", "a script's `name:` does not make it LinkML");
  const names = m.classes.map((c) => c.name).sort();
  assert.deepEqual(names, ["Activity", "Dataset", "Distribution", "Resource"], "Literal and TemporalLiteral are datatypes");
  const ds = m.classes.find((c) => c.name === "Dataset");
  assert.equal(ds.description, "A conceptual entity that represents the information published.");
  const title = ds.properties.find((p) => p.name === "title");
  assert.equal(title.min, 1);
  assert.equal(title.rangeClass, null);
  assert.equal(title.uri, "http://purl.org/dc/terms/title");
  const gen = ds.properties.find((p) => p.name === "wasgeneratedby");
  assert.equal(gen.rangeClass, "Activity");
  assert.equal(gen.label, "was generated by");
  assert.equal(gen.card, "0..*");
});

test("a LinkML schema: slot_usage overrides, prefixes expanded", () => {
  const m = fromLinkML(LINKML, "https://example.org/plus.yaml");
  assert.equal(m.title, "DCAT-AP-PLUS");
  assert.equal(m.version, "0.1.0rc4");
  const gen = m.classes.find((c) => c.name === "Dataset").properties.find((p) => p.name === "was_generated_by");
  assert.equal(gen.rangeClass, "DataGeneratingActivity");
  assert.equal(gen.min, 1);
  assert.equal(gen.card, "1..*");
  assert.equal(gen.uri, "http://www.w3.org/ns/prov#wasGeneratedBy");
  assert.deepEqual(gen.notes, ["stricter than DCAT-AP"]);
  assert.deepEqual(m.classes.find((c) => c.name === "Device").isA, ["AgenticEntity"]);
  assert.throws(() => fromLinkML("a: 1", "x"), /not a LinkML schema/);
});

test("a class diagram around one class", () => {
  const m = fromPropertyTables(HTML, "https://example.org/dcat-ap/");
  const d = classDiagram(m, { focus: "Dataset" });
  assert.match(d, /^classDiagram\n  direction LR/);
  assert.match(d, /\+title Literal \[1\.\.n\]/, "mandatory data properties are members; * is written n");
  assert.doesNotMatch(d, /modificationdate/, "optional data properties are left out by default");
  assert.match(d, /Dataset --> "0\.\.\*" Distribution : dataset distribution/);
  assert.match(d, /Dataset --> "0\.\.\*" Activity : was generated by/);
  assert.doesNotMatch(d, /Distribution --> /, "a focused diagram draws the focus's associations only");
  assert.deepEqual([...neighbourhood(m, "Distribution", 1)].sort(), ["Dataset", "Distribution", "Resource"]);
});

test("the workflow, from PROV-O terms", () => {
  const plus = fromLinkML(LINKML, "p");
  const edges = flowEdges(plus).map((e) => `${e.from} ${e.role} ${e.to}`).sort();
  assert.deepEqual(edges, [
    "AgenticEntity carriedOutBy Activity",
    "DataGeneratingActivity generatedBy Dataset",
    "EvaluatedEntity used DataGeneratingActivity",
    "Plan used DataGeneratingActivity",
  ]);
  const flow = flowDiagram(plus, { highlight: ["Plan"] });
  assert.match(flow, /DataGeneratingActivity\(\["DataGeneratingActivity"\]\)/, "activities are rounded");
  assert.match(flow, /Plan\[\/"Plan"\/\]/, "plans are parallelograms");
  assert.match(flow, /AgenticEntity\{\{"AgenticEntity"\}\}/, "agents are hexagons");
  assert.match(flow, /DataGeneratingActivity ==>\|was generated by\| Dataset/);
  assert.match(flow, /DataGeneratingActivity -\.-\|is a\| Activity/);
  assert.match(flow, /class Plan added/);
  const base = flowDiagram(fromPropertyTables(HTML, "a"));
  assert.match(base, /Activity ==>\|was generated by\| Dataset/, "the base states one edge: the dead end");
});

test("comparing a profile with its base finds the extension", () => {
  const a = fromPropertyTables(HTML, "https://example.org/dcat-ap/");
  const b = fromLinkML(LINKML, "https://example.org/plus.yaml");
  const d = compare(a, b);
  assert.deepEqual(d.addedClasses.map((c) => c.name).sort(), ["AgenticEntity", "DataGeneratingActivity", "Device", "EvaluatedEntity", "Plan"]);
  const ds = d.changes.find((c) => c.class === "Dataset");
  assert.deepEqual(ds.stricter, [{ name: "was_generated_by", from: "0..*", to: "1..*", aAnchor: "Dataset.wasgeneratedby" }]);
  assert.equal(ds.narrowed[0].from, "Activity");
  assert.equal(ds.narrowed[0].to, "DataGeneratingActivity");
  assert.equal(ds.narrowed[0].subclass, true);
  assert.equal(ds.added.length, 0, "dataset distribution matches dcat:distribution by URI despite the different name");
  assert.ok(d.changes.find((c) => c.class === "Activity").added.some((p) => p.name === "carried_out_by"));
  assert.deepEqual(d.missingClasses.map((c) => c.name), ["Resource"]);
  assert.equal(norm("Licence Document"), norm("LicenseDocument"));
});
