#!/usr/bin/env node
// build-packs — project each language's specification into its knowledge pack
// (specification 04 §5). The spec is the source; the pack is a projection:
//
//   specifications/specs/<module>.md  "## N. Language" section
//     → long-grass/knowledge-packs/<pack_id>/{manifest.json, reference.md}
//
// for every catalogue language whose pack is generated (all but vaHera, whose
// pack is hand-written). Fenced examples tagged with the language id are
// validated by the language's own compiler in
// long-grass/test/knowledge-packs.test.mjs.
//
//   node scripts/build-packs.mjs           # write
//   node scripts/build-packs.mjs --check   # exit 1 if a pack is stale
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const cat = JSON.parse(readFileSync(path.join(ROOT, "specifications/registry/catalogue.json"), "utf8"));
const HAND_WRITTEN = new Set(["vahera"]);
const KEYWORDS = {
  turbulance: ["turbulance", "ndombolo", "proposition", "motion", "funxn", "considering"],
  wt: ["wind tunnel", "wind-tunnel", ".wt", "r_est", "holonomy", "regime"],
  sbs: ["sbs", "circuit", "glycolysis", "metabolic", "flux", "perturb"],
  hfq: ["hfq", "federated query", "plan", "budget", "chebi", "rhea"],
  srn: ["srn", "glyph", "sango rine shumba", "pylon"],
  tempus: ["tempus", "timing", "delta p", "cell", "sync"],
  smith: ["smith", "agent smith", "split-attention", "self-graph", "scene", "society"],
  synopsis: ["synopsis", "genomic", "motif", "homology", "residue", "variant", "frame"],
};

function languageSection(md) {
  const lines = md.split(/\r?\n/);
  const start = lines.findIndex((l) => /^## (\d+\. )?Language\s*$/.test(l));
  if (start < 0) return null;
  let end = lines.findIndex((l, i) => i > start && /^## /.test(l));
  if (end < 0) end = lines.length;
  return lines.slice(start + 1, end).join("\n").trim();
}

const check = process.argv.includes("--check");
let stale = 0;
for (const dsl of cat.dsls) {
  if (HAND_WRITTEN.has(dsl.pack_id)) continue;
  const mod = cat.modules.find((m) => m.id === dsl.module_id);
  const specPath = path.join(ROOT, "specifications", mod.spec);
  const section = languageSection(readFileSync(specPath, "utf8"));
  if (!section) throw new Error(`${mod.spec} has no "## Language" section`);
  const reference = [
    `# ${dsl.label} — language reference`,
    "",
    `<!-- GENERATED by scripts/build-packs.mjs from specifications/${mod.spec} — edit the spec, not this file. -->`,
    "",
    `Executed by the \`${dsl.module_id}\` module. File extension \`${dsl.extension}\`. A script is valid iff the language's own compiler accepts it.`,
    "",
    section,
    "",
  ].join("\n");
  const manifest = {
    id: dsl.pack_id,
    name: `${dsl.label} Reference`,
    short_label: dsl.label,
    summary: `Grammar and worked examples for ${dsl.label}, projected from specifications/${mod.spec}. Used to ground natural-language-to-${dsl.id} generation; contains grammar and examples, never domain facts.`,
    source_repo: mod.upstream[0]?.repo ?? "buhera",
    trigger_keywords: KEYWORDS[dsl.id] ?? [dsl.id],
    trigger_match: "any",
    context_budget_tokens: 4000,
    files: [{ path: "reference.md", description: `${dsl.label} grammar and validated examples` }],
  };
  const dir = path.join(ROOT, "long-grass/knowledge-packs", dsl.pack_id);
  const outs = [
    [path.join(dir, "reference.md"), reference],
    [path.join(dir, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n"],
  ];
  for (const [file, text] of outs) {
    const current = existsSync(file) ? readFileSync(file, "utf8") : null;
    if (current === text) continue;
    if (check) {
      console.log(`stale ${path.relative(ROOT, file)}`);
      stale++;
    } else {
      mkdirSync(dir, { recursive: true });
      writeFileSync(file, text);
      console.log(`wrote ${path.relative(ROOT, file)}`);
    }
  }
}
if (check) {
  console.log(stale ? `${stale} stale pack file(s)` : "packs are up to date");
  process.exit(stale ? 1 : 0);
}
